import plecak from 'assets/images/plecak.jpg';
import torebkaRoz from 'assets/images/torebka-roz.jpg';
import jednorozec from 'assets/images/jednorozec.png';
import chusta from 'assets/images/chusta_bg.png';
import kocyk from 'assets/images/kocyk.jpg';
import kocyknos from 'assets/images/kocyknos.jpg';

const initialState = {
  torebki: [
    {
      id: 1,
      title: 'Plecak',
      price: '40 zł',
      desc: ' Plecak na wakacyjne wypady',
      imageUrl: plecak,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'torebki',
    },

    {
      id: 2,
      title: 'Torebka',
      price: '225 zł',
      desc: ' Różowa torebka stylowa',
      imageUrl: torebkaRoz,
      createdTime: '5 dni',
      type: 'Szydełko',
      category: 'torebki',
    },
    {
      id: 3,
      title: 'Torebka',
      price: '225 zł',
      desc: ' Różowa torebka stylowa',
      imageUrl: torebkaRoz,
      createdTime: '5 dni',
      type: 'Szydełko',
      category: 'torebki',
    },
    {
      id: 4,
      title: 'Plecak',
      price: '40 zł',
      desc: ' Plecak na wakacyjne wypady',
      imageUrl: plecak,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'torebki',
    },
    {
      id: 5,
      title: 'Plecak',
      price: '40 zł',
      desc: ' Plecak na wakacyjne wypady',
      imageUrl: plecak,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'torebki',
    },
    {
      id: 6,
      title: 'Torebka',
      price: '225 zł',
      desc: ' Różowa torebka stylowa',
      color: 'Róż',
      imageUrl: torebkaRoz,
      createdTime: '5 dni',
      type: 'Szydełko',
      category: 'torebki',
    },
  ],
  chusty: [
    {
      id: 1,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 2,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 3,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 4,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 5,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 6,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 7,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 8,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
    {
      id: 9,
      title: 'Chusta',
      price: '240 zł',
      desc: ' Chusata na wakacyjne wypady',
      imageUrl: chusta,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'chusty',
    },
  ],
  ubrania: [
    {
      id: 1,
      title: 'Opaska',
      price: '120 zł',
      desc: ' Cienka opaska wsam raz na jesienne wietrzne dni',
      imageUrl: 'https://picsum.photos/200/300',
      createdTime: '10 dni',
      type: 'Druty',
      category: 'ubrania',
    },
    {
      id: 2,
      title: 'Czapka',
      price: '40 zł',
      desc: ' Cienka opaska wsam raz na jesienne wietrzne dni',
      imageUrl: 'https://picsum.photos/200/300',
      createdTime: '10 dni',
      type: 'Druty',
      category: 'ubrania',
    },
    {
      id: 3,
      title: 'Rękawiczki',
      price: '30 zł',
      desc: ' Cienka opaska wsam raz na jesienne wietrzne dni',
      imageUrl: 'https://picsum.photos/200/300',
      createdTime: '6 dni',
      type: 'Druty',
      category: 'ubrania',
    },
    {
      id: 4,
      title: 'Szalik',
      price: '25 zł',
      desc: ' Cienka opaska wsam raz na jesienne wietrzne dni',
      imageUrl: 'https://picsum.photos/200/300',
      createdTime: '5 dni',
      type: 'Druty',
      category: 'ubrania',
    },
    {
      id: 5,
      title: 'Sweter',
      price: '220 zł',
      desc: ' Cienka opaska wsam raz na jesienne wietrzne dni',
      imageUrl: 'https://picsum.photos/200/300',
      createdTime: '15 dni',
      type: 'Druty',
      category: 'ubrania',
    },
  ],
  pluszaki: [
    {
      id: 1,
      title: 'Maskotka',
      price: '30 zł',
      desc: ' Kolorowy jednorożec - dziewczynka',
      imageUrl: jednorozec,
      createdTime: '6 dni',
      type: 'Szydełko',
      category: 'pluszaki',
    },
  ],
  kocyki: [
    {
      id: 1,
      title: 'Kocyk ',
      price: '220 zł',
      desc: 'Kocyk kolorowy dla maluszka',
      imageUrl: kocyk,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'kocyki',
    },
    {
      id: 2,
      title: 'Kocyk - Maskotka',
      price: '220 zł',
      desc: 'Kocyk dla maluszka',
      imageUrl: kocyknos,
      createdTime: '7 dni',
      type: 'Szydełko',
      category: 'kocyki',
    },
    {
      id: 3,
      title: 'Kocyk - Maskotka',
      price: '220 zł',
      desc: 'Kocyk dla maluszka',
      imageUrl: kocyknos,
      createdTime: '7 dni',
      type: 'Szydełko',
      category: 'kocyki',
    },
    {
      id: 4,
      title: 'Kocyk ',
      price: '220 zł',
      desc: 'Kocyk kolorowy dla maluszka',
      imageUrl: kocyk,
      createdTime: '10 dni',
      type: 'Szydełko',
      category: 'kocyki',
    },
  ],
};

export const rootReducer = (state = initialState, action) => {
  return state;
};
